# Generated by Django 6.0.5 on 2026-05-30 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('durasi', models.PositiveIntegerField(help_text='Durasi dalam menit')),
                ('rating_usia', models.CharField(max_length=10)),
                ('sinopsis', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='poster/')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('tanggal_rilis', models.DateField()),
                ('status', models.CharField(choices=[('TAYANG', 'Sedang Tayang'), ('COMING_SOON', 'Coming Soon')], default='TAYANG', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kursi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kursi', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_studio', models.CharField(max_length=50)),
                ('kapasitas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JadwalTayang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('harga_tiket', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_film', to='reservasi.film')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_studio', to='reservasi.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_reservasi', models.CharField(editable=False, max_length=20, unique=True)),
                ('jumlah_tiket', models.PositiveIntegerField(default=1)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('LUNAS', 'Lunas'), ('BATAL', 'Batal'), ('SELESAI', 'Selesai')], default='PENDING', max_length=20)),
                ('tanggal_pesan', models.DateTimeField(auto_now_add=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasi.jadwaltayang')),
                ('kursi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasi.kursi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservasi_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode_pembayaran', models.CharField(choices=[('TRANSFER', 'Transfer Bank'), ('QRIS', 'QRIS')], max_length=50)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/')),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('BERHASIL', 'Berhasil'), ('DITOLAK', 'Ditolak')], default='MENUNGGU', max_length=20)),
                ('reservasi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservasi.reservasi')),
            ],
        ),
        migrations.AddField(
            model_name='kursi',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kursi_studio', to='reservasi.studio'),
        ),
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_tiket', models.CharField(editable=False, max_length=30, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcode/')),
                ('diterbitkan_pada', models.DateTimeField(auto_now_add=True)),
                ('reservasi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservasi.reservasi')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='kursi',
            unique_together={('studio', 'nomor_kursi')},
        ),
    ]
