# Generated by Django 6.0.5 on 2026-06-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasi',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='reservasi',
            unique_together={('jadwal', 'kursi')},
        ),
    ]
