# Generated by Django 6.0.5 on 2026-06-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0002_alter_reservasi_total_harga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiket',
            name='sudah_digunakan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tiket',
            name='waktu_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
